name: Deploy React Frontend via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image & extract static site
      run: |
        docker build -t react-build .
        docker create --name temp-container react-build
        mkdir -p app
        docker cp temp-container:/usr/share/nginx/html app/
        docker rm temp-container

    - name: Copy static files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 140.245.20.132                # your server IP
        username: ubuntu                 # your server user
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "app/html/*"
        target: "/var/www/apies-frontend"
        strip_components: 0
        overwrite: true

    - name: Reload nginx
      uses: appleboy/ssh-action@master
      with:
        host: 140.245.20.132
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo systemctl reload nginx
