name: Deploy to Ubuntu Server via SSH

on:
  push:
    branches:
      - main  #

jobs:
  deploy:
    name: Deploy Node App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy code to server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@140.245.20.132 << 'EOF'
          sudo su
          cd /home/ubuntu/tatvacareapies-main
          git pull origin main
          npm install nodemon
          npm install
          pm2 reload apies || pm2 start index.js --name apies
        EOF
